### PR TITLE
Fix Double encoding on JS

### LINKED ISSUE #155: Issue with JS port: invalid serialization of double
Issue with JS port: invalid serialization of double

_Originally posted by @akuleshov7 in https://github.com/akuleshov7/ktoml/pull/153#discussion_r1008911491_

### PR DESCRIPTION
**Pull request by NightEule5**
Fixes #155

### CODE REVIEW

File: ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/writers/TomlEmitter.kt [hunk 1]
```diff
@@ -223,7 +223,12 @@ public abstract class TomlEmitter(config: TomlOutputConfig) {
                 float.isNaN() -> "nan"
                 float.isInfinite() ->
                     if (float > 0) "inf" else "-inf"
-                else -> float.toString()
+                else -> {
```
Comment (akuleshov7) [inline ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/writers/TomlEmitter.kt:226]: May be need to report/fix in Kotlin? What do you think? Or not a bug

**Review by akuleshov7 — APPROVED** [review]

File: ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/writers/TomlEmitter.kt (hunk 1 above)
Comment (NightEule5) [reply ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/writers/TomlEmitter.kt:226]: I think it is. I'm guessing something to do with JS's dynamic typing
